/* AUTO-GENERATED by build.py — package overrides */
CruCo.config.ASSET_BASE = "";
CruCo.config.SCORM.VERSION = "1.2";
CruCo.config.ALLOW_URL_FLAGS = false;
CruCo.config.DEBUG = false;
CruCo.config.EDITOR = false;
CruCo.config.OVERRIDES = "";
CruCo.buildInfo = {"standard": "1.2", "contentVersion": "1.0.0", "editor": false, "builtAt": "2026-09-27T18:45:50"};
