/* =========================================================================
   uiStrings.js — learner-facing interface text (neutral Spanish)
   -------------------------------------------------------------------------
   Every label the player shows lives here, so nothing in English reaches
   the UI. Placeholders in {braces} are filled at runtime.
   This file is interface microcopy only — course content lives in content/.
   Wording follows the course storyboard: the navigation units are
   "lecciones" and the glossary area is called "Wiki".
   ========================================================================= */
window.CruCo = window.CruCo || {};

CruCo.strings = {
  // ---- Shell ----------------------------------------------------------------
  skipToContent: "Saltar al contenido",
  openMenu: "Abrir menú",
  closeMenu: "Cerrar menú",
  courseMenu: "Menú del curso",
  tabModules: "Lecciones",
  tabGlossary: "Wiki",
  tabHelp: "Ayuda",
  tabDownloads: "Descargas",
  prev: "Anterior",
  next: "Siguiente",
  screenCounter: "Pantalla {n} de {total}",
  durationLabel: "Duración estimada",
  screenAnnounce: "Pantalla {n} de {total}: {title}",
  screenNav: "Navegación entre pantallas",
  progressLabel: "Progreso del curso",
  progressValue: "{pct} %",
  courseCompleted: "Completado",
  courseCompletedToast: "Has completado el curso. Tu progreso quedó registrado.",
  lessonCompletedToast: "Has completado esta lección (vista de revisión).",
  moduleLabel: "Lección {n}",
  lastScreen: "Esta es la última pantalla del curso.",
  navLockedHint: "Responde la actividad para continuar.",
  navRevealingHint: "Espera a que termine de aparecer el contenido.",
  scrollMore: "Ver el resto de la pantalla",

  // ---- Table of contents --------------------------------------------------
  statusDone: "completada",
  statusPending: "actividad pendiente",
  statusNew: "sin visitar",
  statusLocked: "se abrirá al completar la pantalla anterior",
  soon: "próximamente",
  moduleProgress: "{done} de {total} pantallas completadas",

  // ---- Wiki (glosario) ----------------------------------------------------------
  glossarySearch: "Buscar en la Wiki",
  glossaryPlaceholder: "Buscar término…",
  glossaryCount: "{n} términos",
  glossaryCountOne: "1 término",
  glossaryEmpty: "Todavía no hay términos en la Wiki.",
  glossaryNoResults: "No hay resultados para «{q}».",
  glossaryGoTo: "Ver en el curso",

  // ---- Help ------------------------------------------------------------------------
  helpNavTitle: "Cómo navegar",
  helpNavItems: [
    "Usa los botones **Anterior** y **Siguiente** de la parte inferior para avanzar pantalla a pantalla.",
    "Abre el **Menú** para ver las lecciones y saltar a cualquier pantalla ya disponible. Las pantallas completadas se marcan con ✓.",
    "La barra superior muestra la lección en la que estás y tu progreso. Se guarda automáticamente y puedes continuar donde lo dejaste.",
    "Las actividades no son calificables: si te equivocas, pulsa **Repetir** para intentarlo de nuevo. No necesitas acertar para avanzar.",
    "Al final del menú encontrarás **Descargas**, la **Wiki** de términos y la sección de **Ayuda**.",
    "Puedes recorrer todo el curso con el teclado: **Tab** para moverte y **Enter** o **Espacio** para activar."
  ],
  helpSupportTitle: "Soporte",
  helpSupportIntro: "Si tienes algún problema técnico, escríbenos:",
  helpSupportWhatsapp: "WhatsApp",
  helpSupportEmail: "Correo",
  helpSupportPhone: "Teléfono",
  helpSupportHours: "Horario",
  helpSupportLocation: "Ubicación",
  helpSupportUrl: "Centro de ayuda",
  helpTechTitle: "Requisitos técnicos",
  helpTechItems: [
    "Navegador actualizado: Chrome, Edge, Firefox o Safari.",
    "Activa el sonido para escuchar la narración. Cada audio incluye su transcripción.",
    "Si una pantalla no carga bien, recarga la página: tu progreso se conserva."
  ],

  // ---- Downloads ----------------------------------------------------------------
  downloadsIntro: "Materiales complementarios del curso.",
  downloadsEmpty: "Todavía no hay recursos descargables.",

  // ---- Media --------------------------------------------------------------------------
  videoPlaceholderLabel: "Video en producción",
  videoPlaceholderAria: "Espacio reservado para el video: {title}",
  videoFrameTitle: "Video: {title}",
  videoLabel: "Reproductor de video",
  videoPlay: "Reproducir video",
  videoPause: "Pausar video",
  videoStop: "Detener video",
  videoSeek: "Posición del video",
  videoRate: "Velocidad de reproducción: {rate}",
  videoCaptionsShow: "Activar subtítulos",
  videoCaptionsHide: "Desactivar subtítulos",
  videoCaptionsNone: "Subtítulos no disponibles",
  videoFullscreen: "Pantalla completa",
  videoExitFullscreen: "Salir de pantalla completa",
  videoTranscriptShow: "Ver transcripción",
  videoTranscriptHide: "Ocultar transcripción",
  videoUnavailable: "El video no está disponible por el momento.",
  imageUnavailable: "Imagen no disponible",
  audioLabel: "Narración de la pantalla",
  audioPlay: "Reproducir narración",
  audioPause: "Pausar narración",
  audioSeek: "Posición de la narración",
  audioRate: "Velocidad de reproducción: {rate}",
  audioTranscriptShow: "Ver transcripción",
  audioTranscriptHide: "Ocultar transcripción",
  audioUnavailable: "Audio no disponible por el momento.",

  // ---- Interactions --------------------------------------------------------------
  close: "Cerrar",
  flipHintFront: "Girar tarjeta",
  flipHintBack: "Volver",
  timelineHint: "Haz clic sobre las imágenes para descubrir.",
  carouselLabel: "Carrusel",
  carouselSlide: "{n} de {total}",
  carouselPrev: "Anterior",
  carouselNext: "Siguiente",
  carouselGoTo: "Ir a {n}: {title}",
  categorizeTray: "Tarjetas por clasificar",
  categorizeNone: "Sin clasificar",
  categorizeEmpty: "No queda ninguna tarjeta por clasificar.",
  categorizeAssign: "Clasificar «{item}»",
  categorizeDrag: "Arrastra «{item}» a su categoría",
  timelineReveal: "Descubrir",
  hotspotLegend: "Selecciona cada punto para ver más información.",
  hotspotLabel: "Punto {n}: {label}",
  visited: "Visto",

  // ---- Knowledge checks ---------------------------------------------------------
  quizEyebrow: "Autoevaluación",
  quizMeta: "{n} preguntas · Actividad no calificable",
  quizMetaOne: "1 pregunta · Actividad no calificable",
  questionNum: "Pregunta {n} de {total}",
  hintSingle: "Selecciona una respuesta.",
  hintMultiple: "Selecciona todas las respuestas correctas.",
  hintTrueFalse: "Indica si la afirmación es verdadera o falsa.",
  hintMatching: "Relaciona cada elemento con su pareja.",
  hintOrdering: "Arrastra los elementos o usa los botones de subir y bajar para ordenarlos.",
  hintCategorize: "Arrastra cada tarjeta hasta su categoría. También puedes elegirla en la lista de la propia tarjeta.",
  hintFillblank: "Escribe tu respuesta.",
  hintCloze: "Elige la opción correcta en cada espacio.",
  clozeChoose: "Elige…",
  clozeGap: "Espacio {n}",
  hintRecall: "Escribe tu respuesta y después compárala con la respuesta de referencia.",
  optionTrue: "Verdadero",
  optionFalse: "Falso",
  check: "Comprobar",
  retry: "Repetir",
  reveal: "Ver respuesta de referencia",
  feedbackCorrect: "Correcto",
  feedbackIncorrect: "Incorrecto",
  feedbackRecall: "Respuesta de referencia",
  correctAnswerMark: "Respuesta correcta",
  selectPlaceholder: "Selecciona…",
  moveUp: "Subir: {item}",
  moveDown: "Bajar: {item}",
  movedTo: "{item}: posición {pos} de {total}",
  dragHandle: "Arrastrar para reordenar: {item}",
  answerRequired: "Responde antes de comprobar.",
  quizCompleted: "Actividad completada",
  answerLabel: "Tu respuesta",

  // ---- Resume ---------------------------------------------------------------------
  resumeTitle: "¿Quieres continuar donde lo dejaste?",
  resumeBody: "Tu progreso en este curso está guardado.",
  resumeYes: "Continuar",
  resumeNo: "Ir al inicio",

  // ---- Empty course -------------------------------------------------------------
  emptyTitle: "Todavía no hay contenido",
  emptyBody: "Este curso aún no tiene pantallas cargadas.",

  // ---- Editor mode (author only; never present in the LMS build) -----------
  editorBadge: "Modo edición",
  editorEdit: "Editar",
  editorDelete: "Borrar",
  editorDeleteAria: "Borrar: {what}",
  editorDeletedPiece: "{what} · borrado",
  editorDeletedLabel: "Borrado",
  editorRestorePiece: "Restaurar",
  // Names of the pieces, used in the editor toolbars and the changes panel.
  pieceNames: {
    text: "Texto",
    heading: "Título",
    callout: "Mensaje destacado",
    cards: "Tarjetas",
    image: "Imagen",
    video: "Video",
    audio: "Audio",
    accordion: "Acordeón",
    tabs: "Pestañas",
    flipcards: "Tarjetas giratorias",
    layers: "Capas",
    hotspots: "Puntos interactivos",
    quiz: "Actividad",
    badge: "Icono",
    reactions: "Reacciones",
    carousel: "Carrusel",
    background: "Imagen de fondo",
    avatar: "Foto de quien presenta",
    screenAudio: "Narración de la pantalla",
    piece: "Elemento"
  },
  editImage: "Editar imagen",
  editVideo: "Editar video",
  editAudio: "Editar audio",
  editorEdited: "Editado",
  editorDialogImage: "Editar imagen",
  editorDialogVideo: "Editar video",
  editorDialogAudio: "Editar audio",
  editorFieldSrc: "Archivo o enlace",
  editorFieldSrcHelp: "Ruta dentro del curso (assets/…), enlace de Google Drive o URL.",
  editorFieldAlt: "Texto alternativo (accesibilidad)",
  editorFieldCaption: "Pie de foto",
  editorFieldTitle: "Título",
  editorFieldScript: "Guion (VO/Script)",
  editorFieldPoster: "Imagen de portada del video",
  editorFieldCaptions: "Subtítulos (.vtt)",
  editorFieldTranscript: "Transcripción",
  editorPick: "Elegir archivo…",
  editorPickHint: "Copia el archivo en {path} dentro del proyecto para que se vea en el curso final.",
  editorPreviewLocal: "Vista previa temporal del archivo elegido.",
  editorApply: "Aplicar",
  editorCancel: "Cancelar",
  editorRestore: "Restablecer original",
  editorPanel: "Cambios del editor",
  editorPanelOpen: "Abrir el panel de cambios",
  editorPanelEmpty: "Todavía no has hecho cambios.",
  editorCount: "{n} cambios",
  editorCountOne: "1 cambio",
  editorExport: "Descargar overrides.js",
  editorCopy: "Copiar al portapapeles",
  editorCopied: "Copiado",
  editorClear: "Descartar todos los cambios",
  editorClearConfirm: "¿Descartar todos los cambios del editor?",
  editorExportHelp: "Guarda este archivo como content/overrides.js dentro de 02-Prototipo. El paquete del curso lo incluye automáticamente; para verlo también en el prototipo, escribe \"overrides.js\" en OVERRIDES dentro de courseConfig.js.",
  editorFilesPending: "Archivos que debes copiar al proyecto:",
  editorScreen: "Pantalla {id}"
};
