/* =========================================================================
   drive-assets.js — AUTO-GENERATED by 04-Build/build.py --localize-drive
   Maps Google Drive FILE_IDs to local copies in assets/drive/ so Drive
   files keep working offline. Do not edit by hand.
   ========================================================================= */
window.CruCo = window.CruCo || {};
CruCo.assetMap = /*<map>*/{}/*</map>*/;
